server {
    listen 80;
    server_name localhost;

    # 1. API: Todo lo que empiece por /api/ va al backend
    location /api/ {
        proxy_pass http://backend-python:8000/; 
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # 2. LINKS CORTOS
    # IMPORTANTE: Las comillas "" son obligatorias porque usamos {6}
    location ~* "^/[a-zA-Z0-9]{6}$" {
        proxy_pass http://backend-python:8000;
        
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # 3. FRONTEND: Todo lo demás carga la web
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }
}